# Generated by Django 4.1.1 on 2022-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('complain', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
