# Generated by Django 4.1.1 on 2022-10-28 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('contact', models.IntegerField()),
                ('createdon', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept', models.CharField(max_length=300)),
                ('response', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.complaintmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('hod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.authoritymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.deptmodel')),
            ],
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='coursename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.coursemodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
