# Generated by Django 4.1.1 on 2022-10-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
