# Generated by Django 4.1.1 on 2022-10-19 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_authoritymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('reciept', models.CharField(max_length=300)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.complaintmodel')),
            ],
        ),
    ]
