# Generated by Django 4.1.1 on 2022-11-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_responsechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.responsechoice'),
        ),
    ]
